"""Create ImageMeta model

Revision ID: df1541844fa1
Revises: 795b0f10cadd
Create Date: 2024-03-11 13:35:50.387472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1541844fa1'
down_revision = '795b0f10cadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_image_id_shown', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_meta')
    # ### end Alembic commands ###
